@startuml

'!pragma layout vizjs

top to bottom direction
skinparam actorStyle awesome

footer "It has been created with PlantUML"

Actor " Local user "  as LUSER
Actor " Remote user " as RUSER

rectangle "Test client" as TCL1
rectangle "Test client" as TCL2

rectangle "WLAN Router/HotSpot" as ROUT

cloud "  WiFi Network  \n (192.168.x.0) " AS WLAN
cloud "  Public Nework "                  AS WAN

rectangle "HILO device" as HILO

note top of HILO
	Hilo device can be configured as
	WiFI HotSpot or a WLAN connected host
end note

hide <<phisical-device>> stereotype

skinparam component<<phisical-device>> {
	BackgroundColor #aaccee
	'BorderColor #ff4444
	FontSize 20
	FontStyle bold
}

component "\nDevice Under Test" as DUT <<phisical-device>> {
	port "pin00" as DP00
	port "pin01" as DP01 
	port "pin02" as DP02 
	port "pin03" as DP03 
	port "pin04" as DP04 
	port "pin05" as DP05 
	port "pin06" as DP06 
	port "pin07" as DP07 
	port "pin08" as DP08 
	port "pin09" as DP09 
	port "pin10" as DP10 
	port "pin11" as DP11 
	port "pin12" as DP12 
	port "pin13" as DP13 
	port "pin14" as DP14 
	port "pin15" as DP15 
}

LUSER <-down-> TCL1
RUSER <-[#Red]-> TCL2
TCL1  <-down-> WLAN
TCL1  <-[#Blue]-> WLAN
TCL2  <-[#Red]-> WAN
WLAN  <--down-> HILO
WLAN  <-[#Blue]-> ROUT
WAN   <-[#Red]-> ROUT
WLAN  <-[#Red]-> ROUT
WLAN  <-[#Blue]-> HILO
WLAN  <-[#Red]-> HILO

HILO -down- DP00
HILO -down- DP01
HILO -down- DP02
HILO -down- DP03
HILO -down- DP04
HILO -down- DP05
HILO -down- DP06
HILO -down- DP07
HILO -down- DP08
HILO -down- DP09
HILO -down- DP10
HILO -down- DP11
HILO -down- DP12
HILO -down- DP13
HILO -down- DP14
HILO -down- DP15

@enduml
